#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/7d217795-ceb8-436f-8cbc-b645696959be/ # 
title: my-api-new

/myapinew:
  get:
    responses:
      200:
        body:
          application/json:
            example:
              {"message":"hello world"}